version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html/:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./www/html/:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: posts_db
      MYSQL_ROOT_PASSWORD: php02-lite
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
